In [2]:
import pandas as pd

In [45]:
#CARGAMOS NUESTRO ARCHIVO CON LOS DATOS
df_viviendas_california = pd.read_csv('housing.csv')

In [46]:
#DAREMOS UNA PRIMERA OBSERVACION SOBRE LA INFORMACION DE LOS METADATOS
df_viviendas_california.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

OBSERVACIONES:
- Podemos observar de que la mayoria de nuestras columnas son del tipo float y solo la columna ocean proximity es de tipo objeto, por lo que deberemos cambiar el tipo de dato de las columnas. 
- Tambien observamos que en la columna total bedrooms hay una menor cantidad de datos por lo que deberian ser datos nulos.
- Finalmente el nombre de las columnas estan en ingles, por lo que para nuestra comodidad las cambiaremos a sus nombres en espa√±ol.

In [47]:
#HACEMOS UN CONTEO DE LA CANTIDAD DE NULOS POR COLUMNAS
df_viviendas_california.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

Debido a que tenemos 207 nulos en la columna total_bedroooms procederemos a reemplazar estos valores con la media o la mediana.

In [48]:
#UNA RAPIDA DESCRIPCION DE NUESTRO DATASET NOS MOSTRARA LA MEDIA Y LA MEDIANA DE NUESTRAS COLUMNAS.
df_viviendas_california.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [49]:
#VAMOS A VISUALIZAR NUESTRO DATASET
df_viviendas_california

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [50]:
#DEBIDO A QUE TENEMOS DATOS MUY GRANDES Y ALEJADOSDE LA MEDIA, PARA EVITAR UN ALTO SESGO PROCEDEROS A REEMPLAZAR 
#LOS VALORES NULOS CON LA MEDIANA
df_viviendas_california.fillna(435, inplace=True)

In [51]:
#A CONTINUACION PROCEDEREMOS A CAMBIAR EL NOMBRE DE LAS COLUMNAS
df_viviendas_california.rename(columns={'longitude': 'Longitud', 
                                'latitude': 'Latitud', 
                                'housing_median_age': 'Edad media de vivienda',
                                'total_rooms': 'Habitaciones en total',
                                'total_bedrooms': 'Dormitorios en total',
                                'population': 'Poblacion',
                                'households': 'Cantidad de hogares',
                                'median_income': 'Ingreso medio',
                                'median_house_value': 'Valor medio de viviendas',
                                'ocean_proximity': 'Proximidad al oceano'}, inplace=True)

In [52]:
df_viviendas_california.head(50)

,Longitud,Latitud,Edad media de vivienda,Habitaciones en total,Dormitorios en total,Poblacion,Cantidad de hogares,Ingreso medio,Valor medio de viviendas,Proximidad al oceano
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
5,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0,NEAR BAY
6,-122.25,37.84,52.0,2535.0,489.0,1094.0,514.0,3.6591,299200.0,NEAR BAY
7,-122.25,37.84,52.0,3104.0,687.0,1157.0,647.0,3.1200,241400.0,NEAR BAY
8,-122.26,37.84,42.0,2555.0,665.0,1206.0,595.0,2.0804,226700.0,NEAR BAY
9,-122.25,37.84,52.0,3549.0,707.0,1551.0,714.0,3.6912,261100.0,NEAR BAY
10,-122.26,37.85,52.0,2202.0,434.0,910.0,402.0,3.2031,281500.0,NEAR BAY
11,-122.26,37.85,52.0,3503.0,752.0,1504.0,734.0,3.2705,241800.0,NEAR BAY
12,-122.26,37.85,52.0,2491.0,474.0,1098.0,468.0,3.0750,213500.0,NEAR BAY
13,-122.26,37.84,52.0,696.0,191.0,345.0,174.0,2.6736,191300.0,NEAR BAY
14,-122.26,37.85,52.0,2643.0,626.0,1212.0,620.0,1.9167,159200.0,NEAR BAY
15,-122.26,37.85,50.0,1120.0,283.0,697.0,264.0,2.1250,140000.0,NEAR BAY
16,-122.27,37.85,52.0,1966.0,347.0,793.0,331.0,2.7750,152500.0,NEAR BAY
17,-122.27,37.85,52.0,1228.0,293.0,648.0,303.0,2.1202,155500.0,NEAR BAY
18,-122.26,37.84,50.0,2239.0,455.0,990.0,419.0,1.9911,158700.0,NEAR BAY
19,-122.27,37.84,52.0,1503.0,298.0,690.0,275.0,2.6033,162900.0,NEAR BAY
20,-122.27,37.85,40.0,751.0,184.0,409.0,166.0,1.3578,147500.0,NEAR BAY
21,-122.27,37.85,42.0,1639.0,367.0,929.0,366.0,1.7135,159800.0,NEAR BAY
22,-122.27,37.84,52.0,2436.0,541.0,1015.0,478.0,1.7250,113900.0,NEAR BAY
23,-122.27,37.84,52.0,1688.0,337.0,853.0,325.0,2.1806,99700.0,NEAR BAY
24,-122.27,37.84,52.0,2224.0,437.0,1006.0,422.0,2.6000,132600.0,NEAR BAY
25,-122.28,37.85,41.0,535.0,123.0,317.0,119.0,2.4038,107500.0,NEAR BAY
26,-122.28,37.85,49.0,1130.0,244.0,607.0,239.0,2.4597,93800.0,NEAR BAY
27,-122.28,37.85,52.0,1898.0,421.0,1102.0,397.0,1.8080,105500.0,NEAR BAY
28,-122.28,37.84,50.0,2082.0,492.0,1131.0,473.0,1.6424,108900.0,NEAR BAY
29,-122.28,37.84,52.0,729.0,160.0,395.0,155.0,1.6875,132000.0,NEAR BAY
30,-122.28,37.84,49.0,1916.0,447.0,863.0,378.0,1.9274,122300.0,NEAR BAY
31,-122.28,37.84,52.0,2153.0,481.0,1168.0,441.0,1.9615,115200.0,NEAR BAY
32,-122.27,37.84,48.0,1922.0,409.0,1026.0,335.0,1.7969,110400.0,NEAR BAY
33,-122.27,37.83,49.0,1655.0,366.0,754.0,329.0,1.3750,104900.0,NEAR BAY
34,-122.27,37.83,51.0,2665.0,574.0,1258.0,536.0,2.7303,109700.0,NEAR BAY
35,-122.27,37.83,49.0,1215.0,282.0,570.0,264.0,1.4861,97200.0,NEAR BAY
36,-122.27,37.83,48.0,1798.0,432.0,987.0,374.0,1.0972,104500.0,NEAR BAY
37,-122.28,37.83,52.0,1511.0,390.0,901.0,403.0,1.4103,103900.0,NEAR BAY
38,-122.26,37.83,52.0,1470.0,330.0,689.0,309.0,3.4800,191400.0,NEAR BAY
39,-122.26,37.83,52.0,2432.0,715.0,1377.0,696.0,2.5898,176000.0,NEAR BAY
40,-122.26,37.83,52.0,1665.0,419.0,946.0,395.0,2.0978,155400.0,NEAR BAY
41,-122.26,37.83,51.0,936.0,311.0,517.0,249.0,1.2852,150000.0,NEAR BAY
42,-122.26,37.84,49.0,713.0,202.0,462.0,189.0,1.0250,118800.0,NEAR BAY
43,-122.26,37.84,52.0,950.0,202.0,467.0,198.0,3.9643,188800.0,NEAR BAY
44,-122.26,37.83,52.0,1443.0,311.0,660.0,292.0,3.0125,184400.0,NEAR BAY
45,-122.26,37.83,52.0,1656.0,420.0,718.0,382.0,2.6768,182300.0,NEAR BAY
46,-122.26,37.83,50.0,1125.0,322.0,616.0,304.0,2.0260,142500.0,NEAR BAY
47,-122.27,37.82,43.0,1007.0,312.0,558.0,253.0,1.7348,137500.0,NEAR BAY
48,-122.26,37.82,40.0,624.0,195.0,423.0,160.0,0.9506,187500.0,NEAR BAY
49,-122.27,37.82,40.0,946.0,375.0,700.0,352.0,1.7750,112500.0,NEAR BAY

In [53]:
#AHORA PROCEDEMOS A CAMBIAR EL TIPO DE DATO DE LAS COLUMNAS
df_viviendas_california['Dormitorios en total'] = df_viviendas_california['Dormitorios en total'].astype('Int64')
df_viviendas_california['Edad media de vivienda'] = df_viviendas_california['Edad media de vivienda'].astype('Int64')
df_viviendas_california['Habitaciones en total'] = df_viviendas_california['Habitaciones en total'].astype('Int64')
df_viviendas_california['Cantidad de hogares'] = df_viviendas_california['Cantidad de hogares'].astype('Int64')

In [54]:
df_viviendas_california.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Longitud                  20640 non-null  float64
 1   Latitud                   20640 non-null  float64
 2   Edad media de vivienda    20640 non-null  Int64
 3   Habitaciones en total     20640 non-null  Int64
 4   Dormitorios en total      20640 non-null  Int64
 5   Poblacion                 20640 non-null  float64
 6   Cantidad de hogares       20640 non-null  Int64
 7   Ingreso medio             20640 non-null  float64
 8   Valor medio de viviendas  20640 non-null  float64
 9   Proximidad al oceano      20640 non-null  object
dtypes: Int64(4), float64(5), object(1)
memory usage: 1.7+ MB

In [59]:
#AQUI PROCEDEMOS A CAMBIAR LAS FILAS DE LA COLUMNA PROXIMIDAD AL OCEANO A MINUSCULAS.
df_viviendas_california['Proximidad al oceano'] = df_viviendas_california['Proximidad al oceano'].str.capitalize()

In [58]:
df_viviendas_california

,Longitud,Latitud,Edad media de vivienda,Habitaciones en total,Dormitorios en total,Poblacion,Cantidad de hogares,Ingreso medio,Valor medio de viviendas,Proximidad al oceano
0,-122.23,37.88,41,880,129,322.0,126,8.3252,452600.0,Near bay
1,-122.22,37.86,21,7099,1106,2401.0,1138,8.3014,358500.0,Near bay
2,-122.24,37.85,52,1467,190,496.0,177,7.2574,352100.0,Near bay
3,-122.25,37.85,52,1274,235,558.0,219,5.6431,341300.0,Near bay
4,-122.25,37.85,52,1627,280,565.0,259,3.8462,342200.0,Near bay
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374,845.0,330,1.5603,78100.0,Inland
20636,-121.21,39.49,18,697,150,356.0,114,2.5568,77100.0,Inland
20637,-121.22,39.43,17,2254,485,1007.0,433,1.7000,92300.0,Inland
20638,-121.32,39.43,18,1860,409,741.0,349,1.8672,84700.0,Inland
20639,-121.24,39.37,16,2785,616,1387.0,530,2.3886,89400.0,Inland

In [60]:
#EXPORTAREMOS NUESTRO DATASET A UN ARCHIVO CSV
df_viviendas_california.to_csv('viviendas california.csv', index=False)